version: "3.1"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodata
    ports:
      - 27017:27017
volumes:
  mongodata:
    driver: local
