version: "3.1"
services: 
  app: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    links:
      - mongodb
    depends_on:
      - mongodb
    ports: 
      - "9090:9090"
  mongodb:
    image: mongo
    container_name: mongodb
    volumes: 
      - mongodata
volumes: 
    mongodata:
      driver: local