version: "3.1"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodata
    ports:
      - 27017:27017
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    tty: true
    # depends_on:
    #   - mongodb
volumes:
  mongodata:
    driver: local
