name: Main

on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: 14

    - name: Run Lint
      run: |
        yarn install
        yarn lint
      working-directory: ./frontend